version: '3.9'

# Taken from https://faun.pub/managing-mongodb-on-docker-with-docker-compose-26bf8a0bbae3

services:
  mongo:
    container_name: mongo
    image: 'mongo'
    restart: always
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=Test1234!'
      - 'MONGO_INITDB_DATABASE=api'
    volumes:
      - './data/db:/data/db'
    ports:
      - '27017:27017'

